const ladderPlayers = ['민진', '성구', '남우', '태원', '혜빈', '민경'];
const scoreboardPlayers = ['성구', '남우', '태원', '민진'];
const storageKey = 'today-team-game-v2';
const historicalRounds = [
  { label:'1회차', changes:{성구:6000, 남우:0, 태원:0, 민진:-6000} },
  { label:'2회차', changes:{성구:-18000, 남우:12000, 태원:0, 민진:6000} },
  { label:'3회차', changes:{성구:17000, 남우:17000, 태원:-17000, 민진:-17000} },
  { label:'4회차', changes:{성구:0, 남우:12000, 태원:-6000, 민진:-6000} },
  { label:'5회차 (프리장)', changes:{성구:0, 남우:7000, 태원:16000, 민진:-23000} },
  { label:'6회차', changes:{성구:-6000, 남우:6000, 태원:0, 민진:0} },
  { label:'7회차', changes:{성구:-3000, 남우:-3000, 태원:3000, 민진:3000} },
  { label:'8회차', changes:{성구:6000, 남우:-6000, 태원:0, 민진:0} }
];
const supabaseUrl = 'https://rqjktefgudohqkfnfkqx.supabase.co';
const supabaseKey = 'sb_publishable_VCByoPczOrmS7EejQNsa4Q_0906hKjL';
const migrationKey = `${storageKey}-supabase-migrated-v1`;
const db = window.supabase?.createClient(supabaseUrl, supabaseKey);
function normaliseSharedRound(round){if(!round||typeof round.id!=='string')return null;const team=(value)=>Array.isArray(value)?value.filter(player=>ladderPlayers.includes(player)):[];const rungs=Array.isArray(round.rungs)?round.rungs.map(row=>Array.isArray(row)?row.filter(col=>Number.isInteger(col)&&col>=0&&col<5):[]):[];const endpointTeams=Array.isArray(round.endpointTeams)&&round.endpointTeams.length===ladderPlayers.length?round.endpointTeams.map(value=>String(value)==='2'?'2':'1'):['1','1','1','2','2','2'];const paths=Array.isArray(round.paths)?round.paths.map(path=>({start:Number(path.start)||0,lanes:Array.isArray(path.lanes)?path.lanes.filter(lane=>Number.isInteger(lane)&&lane>=0&&lane<ladderPlayers.length):[],endLane:Number(path.endLane)||0})):[];return {id:round.id,date:typeof round.date==='string'?round.date:null,createdAt:typeof round.createdAt==='string'?round.createdAt:null,team1:team(round.team1),team2:team(round.team2),rungs,endpointTeams,paths,results:Array.isArray(round.results)?round.results.map(value=>String(value)==='2'?'2':'1'):[],winnerTeam:round.winnerTeam===1||round.winnerTeam===2?round.winnerTeam:null};}
function normalise(value){const sharedRounds=Array.isArray(value?.sharedRounds)?value.sharedRounds.map(normaliseSharedRound).filter(Boolean):[];const activeSharedRoundId=typeof value?.activeSharedRoundId==='string'&&sharedRounds.some(round=>round.id===value.activeSharedRoundId)?value.activeSharedRoundId:(sharedRounds[sharedRounds.length-1]?.id||null);const nextHyeBinTeam=value?.nextHyeBinTeam===2?2:1;return {matches:Array.isArray(value?.matches)?value.matches:[],nextHyeBinTeam,nextSharedHyeBinTeam:value?.nextSharedHyeBinTeam===2?2:nextHyeBinTeam,sharedRounds,activeSharedRoundId};}
let localSnapshot;
try { localSnapshot=normalise(JSON.parse(localStorage.getItem(storageKey)||'{}')); }
catch { localSnapshot=normalise({}); }
let state = localSnapshot;
let ready = false;
let working = false;
let pending = Promise.resolve();
let syncWarningShown = false;
let selectedSharedWinner = null;
let selectedSharedRoundId = null;
const ladderRowCount = 9;
const ladderTop = 43;
const ladderXs = [70, 194, 318, 442, 566, 690];
const $ = (id) => document.getElementById(id);
const today = new Date().toISOString().slice(0, 10);
function backup(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch(error){console.warn('Local backup failed',error);}}
function setBusy(value){working=value;for(const id of ['drawSharedTeams','confirmReset','resetData','cancelSharedAssignment']){const control=$(id);if(control)control.disabled=value||!ready;}$('resultForm').querySelector('button[type="submit"]').disabled=value||!ready;document.querySelectorAll('.remove-match,.shared-winner-options button').forEach(button=>button.disabled=value||!ready);const save=$('saveSharedWinner');if(save)save.disabled=value||!ready||!selectedSharedWinner||selectedSharedRoundId!==state.activeSharedRoundId;}
function applyState(value){state=normalise(value);backup();renderAll();renderSharedLadder();setBusy(working);}
async function readServer(){const {data,error}=await db.from('scoreboard_state').select('game_state').eq('id',1).single();if(error)throw error;return data.game_state||{};}
// Compare the complete JSON value so two browsers cannot silently overwrite each other.
async function changeServer(change){for(let attempt=0;attempt<8;attempt++){const raw=await readServer();const base=normalise(raw);const next=change(base,raw);if(!next)return base;const {data,error}=await db.from('scoreboard_state').update({game_state:next}).eq('id',1).eq('game_state',JSON.stringify(raw)).select('game_state');if(error)throw error;if(data?.length)return normalise(data[0].game_state);}throw new Error('동시에 변경된 기록이 많아 저장하지 못했습니다. 다시 시도해 주세요.');}
function enqueue(change,success){pending=pending.catch(()=>{}).then(async()=>{setBusy(true);try{const saved=await changeServer(change);applyState(saved);if(success)showToast(success);return true;}catch(error){console.error('Scoreboard save failed',error);showToast('서버 저장에 실패했습니다. 다시 시도해 주세요.');return false;}finally{setBusy(false);}});return pending;}
async function refresh(){if(!ready||working)return;try{const latest=normalise(await readServer());if(JSON.stringify(latest)!==JSON.stringify(state))applyState(latest);syncWarningShown=false;}catch(error){console.error('Scoreboard refresh failed',error);if(!syncWarningShown){showToast('동기화에 실패했습니다. 새로고침해 주세요.');syncWarningShown=true;}}}
function queueRefresh(){pending=pending.catch(()=>{}).then(refresh);}
function formatDate(value){return new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${value}T00:00:00`));}
function formatHistoryDate(value){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${value}T00:00:00`));}
function formatWon(value){return `${value<0?'−':''}${Math.abs(value).toLocaleString()}원`;}
function formatChange(value){return `${value>0?'+':value<0?'−':''}${Math.abs(value).toLocaleString()}원`;}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function totalChange(changes){return scoreboardPlayers.reduce((sum,player)=>sum+Number(changes[player]||0),0);}
function getPlayerStats(){const stats=Object.fromEntries(ladderPlayers.map(name=>[name,{points:0,wins:0,losses:0}]));[...historicalRounds,...state.matches].forEach(entry=>scoreboardPlayers.forEach(player=>{stats[player].points+=Number(entry.changes?.[player]||0);}));state.sharedRounds.forEach(round=>{if(round.winnerTeam!==1&&round.winnerTeam!==2)return;for(const player of round.team1){if(stats[player])round.winnerTeam===1?stats[player].wins+=1:stats[player].losses+=1;}for(const player of round.team2){if(stats[player])round.winnerTeam===2?stats[player].wins+=1:stats[player].losses+=1;}});return stats;}
function winRate(stats){const games=stats.wins+stats.losses;return games?Math.round(stats.wins/games*100):0;}
function renderDashboard(){const stats=getPlayerStats(),ordered=scoreboardPlayers.map(name=>({name,...stats[name]})).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name,'ko'));$('scoreboard').innerHTML=ordered.map((p,i)=>`<div class="rank-row money-rank"><span class="rank ${i===0||p.points>0?'medal':''}">${String(i+1).padStart(2,'0')}</span><strong class="player-name">${p.name}</strong><span class="score-points"><b>누적</b><em>${formatWon(p.points)}</em></span></div>`).join('');$('totalGames').textContent=historicalRounds.length+state.matches.length;const top=ordered[0],bottom=ordered[ordered.length-1];$('topWinner').textContent=`갓${top.name.slice(1)}`;$('topWinnerDetail').textContent=`누적 1위 · ${formatWon(top.points)}`;$('liquidityProvider').textContent=`족${bottom.name.slice(1)}`;$('liquidityProviderDetail').textContent=`누적 4위 · ${formatWon(bottom.points)}`;const recent=state.matches[state.matches.length-1],recentEarner=$('recentEarner'),recentDetail=$('recentEarnerDetail');if(recent){const largest=Math.max(...scoreboardPlayers.map(player=>Number(recent.changes?.[player]||0))),earners=scoreboardPlayers.filter(player=>Number(recent.changes?.[player]||0)===largest);recentEarner.textContent=earners.map(player=>`${player.slice(-1)}황`).join(', ');recentDetail.textContent=`최근 기록 · ${formatWon(largest)}`;}else{recentEarner.textContent='-';recentDetail.textContent='입력된 경기 기록이 없어요.';}$('historyCount').textContent=`${historicalRounds.length+state.matches.length} RECORDS`;}
function ladderRowY(row,height){return ladderTop+((height-45-ladderTop)/(ladderRowCount+1))*(row+1);}
function traceLadder(start,rungs){let lane=start;const lanes=[lane];for(const row of rungs){if(row.includes(lane))lane+=1;else if(row.includes(lane-1))lane-=1;lanes.push(lane);}return {start,lanes,endLane:lane};}
function createRotatingThreeByThreeLadder(preferredHyeBinTeam){const rungs=[];for(let row=0;row<ladderRowCount;row+=1){const rowRungs=[];for(const col of shuffle([0,1,2,3,4])){if(Math.random()<.56&&!rowRungs.includes(col-1)&&!rowRungs.includes(col+1))rowRungs.push(col);}if(!rowRungs.length)rowRungs.push(Math.floor(Math.random()*5));rowRungs.sort((a,b)=>a-b);rungs.push(rowRungs);}const paths=ladderPlayers.map((_,index)=>traceLadder(index,rungs));const hyeBinTeam=String(preferredHyeBinTeam),minKyeongTeam=hyeBinTeam==='1'?'2':'1',hyeBinPartners=new Set(shuffle(ladderPlayers.slice(0,4)).slice(0,2));const results=ladderPlayers.map((player,index)=>index===4?hyeBinTeam:index===5?minKyeongTeam:hyeBinPartners.has(player)?hyeBinTeam:minKyeongTeam);const endpointTeams=Array(ladderPlayers.length);paths.forEach(path=>{endpointTeams[path.endLane]=results[path.start];});return {rungs,endpointTeams,paths,results};}
function drawLadderModel(canvasId,assignment){const canvas=$(canvasId);if(!canvas)return;const ctx=canvas.getContext('2d'),h=canvas.height,bottom=h-45;ctx.clearRect(0,0,canvas.width,h);ctx.strokeStyle='#c9d2e6';ctx.lineWidth=2;ctx.setLineDash([4,5]);ladderXs.forEach(x=>{ctx.beginPath();ctx.moveTo(x,ladderTop);ctx.lineTo(x,bottom);ctx.stroke();});ctx.setLineDash([]);if(!assignment)return;ctx.strokeStyle='#7d95de';ctx.lineWidth=3;for(let row=0;row<assignment.rungs.length;row+=1){const y=ladderRowY(row,h);for(const col of assignment.rungs[row]){ctx.beginPath();ctx.moveTo(ladderXs[col],y);ctx.lineTo(ladderXs[col+1],y);ctx.stroke();}}for(const path of assignment.paths){let lane=path.start;ctx.beginPath();ctx.moveTo(ladderXs[lane],ladderTop);for(let row=0;row<ladderRowCount;row+=1){const y=ladderRowY(row,h);const nextLane=path.lanes[row+1]??lane;ctx.lineTo(ladderXs[lane],y);if(nextLane!==lane)ctx.lineTo(ladderXs[nextLane],y);lane=nextLane;}ctx.lineTo(ladderXs[lane],bottom);ctx.strokeStyle=assignment.results[path.start]==='1'?'rgba(40,87,238,.56)':'rgba(243,72,114,.56)';ctx.lineWidth=5;ctx.lineCap='round';ctx.stroke();ctx.fillStyle=assignment.results[path.start]==='1'?'#2857ee':'#f34872';ctx.beginPath();ctx.arc(ladderXs[lane],bottom,5,0,Math.PI*2);ctx.fill();}}
function renderTargets(targetId,assignment){const targetTeams=assignment?.endpointTeams||['1','1','1','2','2','2'];$(targetId).innerHTML=targetTeams.map(team=>`<span class="${team==='1'?'team-one':'team-two'}">${team} TEAM</span>`).join('');}
function getActiveSharedRound(){return state.sharedRounds.find(round=>round.id===state.activeSharedRoundId)||null;}
function renderSharedLadder(){const round=getActiveSharedRound();$('sharedLadderPlayers').innerHTML=ladderPlayers.map(p=>`<span>${p}</span>`).join('');renderTargets('sharedLadderTargets',round);drawLadderModel('sharedLadderCanvas',round);const empty=$('sharedAssignmentEmpty'),result=$('sharedAssignmentResult'),outcome=$('sharedOutcomeForm'),status=$('sharedLiveStatus');if(!round){selectedSharedWinner=null;selectedSharedRoundId=null;empty.hidden=false;result.hidden=true;outcome.hidden=true;status.textContent='아직 공유된 3:3 팀 배정이 없습니다.';return;}empty.hidden=true;result.hidden=false;result.innerHTML=teamCard(1,round.team1)+teamCard(2,round.team2);if(round.winnerTeam){selectedSharedWinner=null;selectedSharedRoundId=null;outcome.hidden=true;status.textContent=`${round.date?formatHistoryDate(round.date):'3:3 경기'} · ${round.winnerTeam} TEAM 승리 결과가 저장되어 모두에게 공유되었습니다.`;}else{if(selectedSharedRoundId!==round.id){selectedSharedWinner=null;selectedSharedRoundId=round.id;}outcome.hidden=false;status.textContent=`${round.date?formatHistoryDate(round.date):'3:3 경기'} · 팀 배정 완료, 승리 팀을 선택해 결과를 저장하세요.`;renderSharedOutcomeControls();}}
function renderSharedOutcomeControls(){const activeId=state.activeSharedRoundId;document.querySelectorAll('.shared-winner-options [data-winner]').forEach(button=>{const selected=Number(button.dataset.winner)===selectedSharedWinner&&selectedSharedRoundId===activeId;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});const summary=$('sharedOutcomeSelection');if(summary)summary.textContent=selectedSharedWinner&&selectedSharedRoundId===activeId?`${selectedSharedWinner} TEAM 승리를 저장할 준비가 됐습니다.`:'승리 팀을 선택해 주세요.';setBusy(working);}
function teamCard(team,members){return `<div class="team-result ${team===2?'team2':''}"><h3><b>${team} TEAM</b> · ${team===1?'BLUE SIDE':'RED SIDE'}</h3><div class="member-chips">${members.map(p=>`<span>${p}</span>`).join('')}</div></div>`;}
function assignSharedTeams(){if(!ready||working)return;enqueue(base=>{const ladder=createRotatingThreeByThreeLadder(base.nextSharedHyeBinTeam);const team1=[],team2=[];ladder.results.forEach((team,index)=>(team==='1'?team1:team2).push(ladderPlayers[index]));const round={id:crypto.randomUUID(),date:today,createdAt:new Date().toISOString(),...ladder,team1,team2,winnerTeam:null};return {...base,sharedRounds:[...base.sharedRounds,round],activeSharedRoundId:round.id,nextSharedHyeBinTeam:base.nextSharedHyeBinTeam===1?2:1};},'무작위 3:3 팀 배정 결과가 모두에게 전송됐어요!');}
function chooseSharedWinner(event){const button=event.target.closest('[data-winner]');if(!button||!ready||working)return;selectedSharedWinner=Number(button.dataset.winner);selectedSharedRoundId=state.activeSharedRoundId;renderSharedOutcomeControls();}
function recordSharedWinner(){if(!ready||working||!selectedSharedWinner||selectedSharedRoundId!==state.activeSharedRoundId)return;const winnerTeam=selectedSharedWinner,activeId=selectedSharedRoundId;enqueue(base=>{const round=base.sharedRounds.find(item=>item.id===activeId);if(!round||round.winnerTeam)return null;return {...base,sharedRounds:base.sharedRounds.map(item=>item.id===activeId?{...item,winnerTeam}:item)};},`${winnerTeam} TEAM 승리 결과를 저장했어요. 승리 팀은 1승, 상대 팀은 1패가 반영됩니다.`);}
function cancelSharedAssignment(){if(!ready||working)return;const activeId=state.activeSharedRoundId;enqueue(base=>{const round=base.sharedRounds.find(item=>item.id===activeId);if(!round||round.winnerTeam)return null;const sharedRounds=base.sharedRounds.filter(item=>item.id!==activeId);const nextSharedHyeBinTeam=round.team2.includes('혜빈')?2:1;return {...base,sharedRounds,activeSharedRoundId:sharedRounds[sharedRounds.length-1]?.id||null,nextSharedHyeBinTeam};},'이번 3:3 팀 배정을 취소했어요.');}
function renderHistory(){const body=$('historyBody'),items=[...historicalRounds.map((entry,index)=>({...entry,id:`seed-${index}`,date:null,seed:true})),...state.matches].reverse();body.innerHTML=items.map(entry=>`<tr><td>${entry.date?formatHistoryDate(entry.date):`${entry.label} · 날짜 미상`}</td><td class="result-summary">${scoreboardPlayers.map(p=>`<b>${p}</b> ${formatChange(entry.changes[p])}`).join(' · ')}</td><td>${entry.seed?'':`<button class="remove-match" aria-label="기록 삭제" data-id="${entry.id}">×</button>`}</td></tr>`).join('');$('emptyHistory').hidden=true;}
function renderSharedWinRates(){const stats=getPlayerStats();$('sharedWinRates').innerHTML=ladderPlayers.map(player=>{const entry=stats[player],games=entry.wins+entry.losses,rate=winRate(entry),tone=rate>50?'above-even':rate===50?'even':'below-even';return `<div class="shared-winrate-card"><strong>${player}</strong><b class="${tone}">${rate}%</b><small>${games?`${entry.wins}승 · ${entry.losses}패`:'아직 경기 없음'}</small></div>`;}).join('');}
function sharedRoundCard(round){const team=(number,members)=>`<span class="team-${number===1?'one':'two'} ${round.winnerTeam===number?'winning-team':''}"><b>${number} TEAM</b><em>${members.join(' · ')}</em>${round.winnerTeam===number?'<i class="win-badge">WIN</i>':''}</span>`;return `<article class="shared-round-record"><div class="shared-round-meta"><strong>${round.date?formatHistoryDate(round.date):'날짜 미상'}</strong><span class="${round.winnerTeam?'shared-round-winner':''}">${round.winnerTeam?`${round.winnerTeam} TEAM 승리`:'승패 입력 대기'}</span></div><div class="shared-round-teams">${team(1,round.team1)}${team(2,round.team2)}</div></article>`;}
function renderSharedHistory(){const rounds=[...state.sharedRounds].reverse(),recent=rounds.slice(0,5),older=rounds.slice(5),groups=new Map();older.forEach(round=>{const key=round.date||'unknown';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(round);});$('sharedHistoryCount').textContent=`${rounds.length} ROUNDS`;$('sharedHistoryEmpty').hidden=rounds.length>0;const recentMarkup=recent.length?`<p class="shared-history-caption">최근 5경기</p>${recent.map(sharedRoundCard).join('')}`:'';const olderMarkup=groups.size?`<div class="shared-history-older"><p class="shared-history-caption">날짜별 이전 기록</p>${[...groups.entries()].map(([date,items])=>`<details class="shared-history-day"><summary><strong>${date==='unknown'?'날짜 미상':formatHistoryDate(date)}</strong><span>${items.length}경기 · 펼치기</span></summary><div>${items.map(sharedRoundCard).join('')}</div></details>`).join('')}</div>`:'';$('sharedHistoryBody').innerHTML=recentMarkup+olderMarkup;}
function renderSharedCombinationCounts(){const counts=new Map();state.sharedRounds.forEach(round=>[round.team1,round.team2].forEach((members,index)=>{if(members.length!==3)return;const players=[...members].sort((a,b)=>ladderPlayers.indexOf(a)-ladderPlayers.indexOf(b)),key=players.join('|'),team=index+1;const entry=counts.get(key)||{players,count:0,wins:0,losses:0};entry.count+=1;if(round.winnerTeam===team)entry.wins+=1;if(round.winnerTeam&&(round.winnerTeam===1||round.winnerTeam===2)&&round.winnerTeam!==team)entry.losses+=1;counts.set(key,entry);}));const items=[...counts.values()].sort((a,b)=>b.count-a.count||a.players.join('').localeCompare(b.players.join(''),'ko'));$('sharedCombinationCounts').innerHTML=items.length?items.map(item=>`<div class="shared-combination-row"><span>${item.players.join(' · ')}</span><b><i class="combination-count">${item.count}회</i><i class="combination-wins">${item.wins}승</i><i class="combination-losses">${item.losses}패</i></b></div>`).join(''):'<p class="shared-combination-empty">아직 팀 조합 기록이 없어요.</p>';}
function showToast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300);}
$('drawSharedTeams').addEventListener('click',assignSharedTeams);
document.querySelector('.shared-winner-options').addEventListener('click',chooseSharedWinner);
$('saveSharedWinner').addEventListener('click',recordSharedWinner);
$('cancelSharedAssignment').addEventListener('click',cancelSharedAssignment);
$('resultForm').addEventListener('submit',async event=>{event.preventDefault();if(!ready||working)return;const changes={성구:Number($('amountSeonggu').value),남우:Number($('amountNamu').value),태원:Number($('amountTaewon').value),민진:Number($('amountMinjin').value)};const match={id:crypto.randomUUID(),date:$('matchDate').value,changes};if(await enqueue(base=>({...base,matches:[...base.matches,match]}),'개인 금액 기록이 저장됐어요.')){$('resultForm').reset();$('matchDate').value=today;}});
$('historyBody').addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(!button||!ready||working)return;if(!confirm('정말로 삭제하시겠습니까?'))return;const id=button.dataset.id;enqueue(base=>({...base,matches:base.matches.filter(m=>String(m.id)!==id)}),'기록을 삭제했어요.');});
$('resetData').addEventListener('click',()=>{$('resetModal').hidden=false;});
$('cancelReset').addEventListener('click',()=>{$('resetModal').hidden=true;});
$('confirmReset').addEventListener('click',async()=>{if(!ready||working)return;if(await enqueue(()=>({matches:[],nextHyeBinTeam:1,nextSharedHyeBinTeam:1,sharedRounds:[],activeSharedRoundId:null}),'추가 기록을 초기화했어요.')){renderSharedLadder();$('resetModal').hidden=true;}});
function renderAll(){renderDashboard();renderHistory();renderSharedWinRates();renderSharedHistory();renderSharedCombinationCounts();}
$('matchDate').value=today;renderAll();renderSharedLadder();setBusy(false);window.addEventListener('resize',()=>drawLadderModel('sharedLadderCanvas',getActiveSharedRound()));
async function initialise(){if(!db){showToast('동기화 라이브러리를 불러오지 못했습니다. 새로고침해 주세요.');return;}try{let server=await readServer();if(!localStorage.getItem(migrationKey)&&(localSnapshot.matches.length||localSnapshot.nextHyeBinTeam===2)){server=await changeServer((base,raw)=>{const ids=new Set(base.matches.map(m=>String(m.id)));const missing=localSnapshot.matches.filter(m=>!ids.has(String(m.id)));const empty=Object.keys(raw).length===0;return missing.length||empty&&localSnapshot.nextHyeBinTeam===2?{...base,matches:[...base.matches,...missing],nextHyeBinTeam:empty?localSnapshot.nextHyeBinTeam:base.nextHyeBinTeam}:null;});}applyState(server);localStorage.setItem(migrationKey,'1');ready=true;setBusy(false);db.channel('scoreboard-state-1').on('postgres_changes',{event:'UPDATE',schema:'public',table:'scoreboard_state'},queueRefresh).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')queueRefresh();});setInterval(queueRefresh,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)queueRefresh();});}catch(error){console.error('Scoreboard initialisation failed',error);showToast('서버 연결에 실패했습니다. 기록은 이 브라우저에 보관되어 있습니다.');}}
initialise();

