// No network calls: all saves and subscriptions below use an in-memory server.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const path=require('node:path'),root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/initialise\(\);\s*$/,'');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
const amounts=(n=0)=>({남우:n,태원:-n,성구:0,민진:0});
const round=(id,winnerTeam=1)=>({id,date:'2026-09-30',team1:['남우','태원','혜빈'],team2:['민진','성구','민경'],winnerTeam});
const ledger=(extra={})=>({id:'ledger-one',date:'2026-09-30',stake:3000,draft:amounts(),rounds:[],...extra});
function setup(initial={},options={}){
  let server=clone(initial),reads=0,writes=0,beforeUpdate=null,readError=null,writeError=null;
  const elements=new Map(),storage=new Map(Object.entries(options.storage||{})),subscriptions=[],intervals=[];
  function el(id){if(!elements.has(id))elements.set(id,{id,hidden:false,disabled:false,value:'',textContent:'',innerHTML:'',dataset:{},listeners:{},attrs:{},classList:{add(){},remove(){},toggle(){}},setAttribute(k,v){this.attrs[k]=v;},addEventListener(name,fn){this.listeners[name]=fn;},querySelector(){return el('submit');},focus(){},reset(){},getContext(){return new Proxy({},{get(){return ()=>{};}});},width:760,height:330});return elements.get(id);}
  for(const match of html.matchAll(/id="([^"]+)"/g))el(match[1]);
  const choices=[3000,5000].map(n=>{const b=el(`stake${n}`);b.dataset.ledgerStake=String(n);return b;});
  const playerControls=['남우','태원','성구','민진'].flatMap(player=>[1,-1].map(direction=>{const b=el(`${player}${direction}`);b.dataset={ledgerPlayer:player,ledgerDirection:String(direction)};return b;}));
  const document={hidden:false,getElementById:el,addEventListener(){},querySelector(){return el('query');},querySelectorAll(selector){if(selector.includes('data-ledger-stake'))return choices;if(selector.includes('data-ledger-player'))return playerControls;return [];}};
  const db={from(){const filters={};let update=null;return {select(){if(update)return (async()=>{writes++;if(writeError)return {error:writeError};if(beforeUpdate){const fn=beforeUpdate;beforeUpdate=null;fn();}const expected=filters['game_state->revision'];if(expected!==server.revision&&!(expected===null&&server.revision===undefined))return {data:[]};server=clone(update.game_state);return {data:[{game_state:clone(server)}]};})();return this;},eq(k,v){filters[k]=v;return this;},is(k,v){filters[k]=v;return this;},update(value){update=value;return this;},async single(){reads++;return readError?{error:readError}:{data:{game_state:clone(server)}};}};},channel(){return {on(name,filter,fn){subscriptions.push(fn);return this;},subscribe(fn){fn('SUBSCRIBED');return this;}};}};
  const context=vm.createContext({document,window:{supabase:options.noSdk?undefined:{createClient(){return db;}},addEventListener(){}},localStorage:{getItem(k){if(options.blockStorage)throw Error('Storage denied');return storage.get(k)||null;},setItem(k,v){if(options.blockStorage)throw Error('Storage denied');storage.set(k,v);}},crypto:{randomUUID:crypto.randomUUID},console:{warn(){},error(){}},setTimeout(){},setInterval(fn){intervals.push(fn);},confirm:()=>options.confirm!==false,Intl,Date});
  vm.runInContext(source,context);
  const run=code=>vm.runInContext(code,context);
  return {el,choices,run,async init(){await run('initialise()');},async act(code){run(code);await run('pending');},state(){return clone(run('state'));},get server(){return clone(server);},set server(value){server=clone(value);},get reads(){return reads;},get writes(){return writes;},conflict(fn){beforeUpdate=fn;},setReadError(error){readError=error;},setWriteError(error){writeError=error;},storage,subscriptions,intervals};
}
const cases=[];function test(name,fn){cases.push([name,fn]);}
test('HTML control identifiers are unique and referenced controls exist',()=>{const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const m of source.matchAll(/\$\('([^']+)'\)/g))assert(ids.includes(m[1]),m[1]);assert(!html.includes('id="postSettlement"'));});
test('Empty server starts successfully and retains the eight fixed rounds',async()=>{const a=setup();await a.init();assert.equal(a.run('ready'),true);assert.equal(a.el('totalGames').textContent,8);assert.equal(a.state().matches.length,0);assert.equal(a.writes,0);});
test('Local migration merges by ID once and preserves existing server records',async()=>{const old={matches:[{id:'old',date:'2026-09-20',changes:amounts(3000)}]};const a=setup({matches:[{id:'live',date:'2026-09-30',changes:amounts(5000)}],revision:1},{storage:{'today-team-game-v2':JSON.stringify(old)}});await a.init();assert.deepEqual(a.server.matches.map(x=>x.id),['live','old']);await a.init();assert.equal(a.writes,1);});
test('Migration marker prevents deleted records from returning',async()=>{const a=setup({}, {storage:{'today-team-game-v2-supabase-migrated-v1':'1','today-team-game-v2':JSON.stringify({matches:[{id:'deleted',changes:amounts()}]})}});await a.init();assert.equal(a.state().matches.length,0);assert.equal(a.writes,0);});
test('Blocked browser storage does not block a working server',async()=>{const a=setup({revision:1},{blockStorage:true});await a.init();assert.equal(a.run('ready'),true);await a.act('assignSharedTeams()');assert.equal(a.state().sharedRounds.length,1);});
test('Missing SDK leaves save controls disabled',async()=>{const a=setup({}, {noSdk:true});await a.init();assert.equal(a.run('ready'),false);assert.equal(a.el('drawSharedTeams').disabled,true);});
test('Failed startup preserves local records',async()=>{const old={matches:[{id:'local',date:'2026-09-30',changes:amounts(3000)}]};const a=setup({}, {storage:{'today-team-game-v2':JSON.stringify(old)}});a.setReadError(Error('offline'));await a.init();assert.equal(a.run('ready'),false);assert.equal(a.state().matches[0].id,'local');});
test('Malformed dates and incomplete records do not crash rendering',async()=>{const a=setup({matches:[null,{id:'broken',date:'invalid',changes:null}],sharedRounds:[round('r')]});await a.init();assert.equal(a.run('ready'),true);assert(a.el('historyBody').innerHTML.includes('날짜 미상'));assert.equal(a.run("validGameDate('2026-02-30')"),false);assert.equal(a.run("validGameDate('2024-02-29')"),true);});
test('Stored record IDs cannot inject HTML attributes',()=>{const a=setup();const markup=a.run(`sharedRoundCard({...normaliseSharedRound(${JSON.stringify(round('" autofocus onfocus="bad'))})})`);assert(markup.includes('&quot;'));assert(!markup.includes('data-shared-id="" autofocus'));});
test('10,000 ladders have 3:3 teams, opposite fixed pair, and matching real paths',()=>{const a=setup();const result=a.run(`(()=>{let hyeTeam1=0;const pairs=new Set();for(let i=0;i<10000;i++){const ladder=createRotatingThreeByThreeLadder();if(ladder.results.filter(x=>x==='1').length!==3||ladder.results[4]===ladder.results[5])throw Error('Invalid teams');if(new Set(ladder.paths.map(p=>p.endLane)).size!==6)throw Error('Paths overlap');for(const p of ladder.paths)if(ladder.endpointTeams[p.endLane]!==ladder.results[p.start])throw Error('Wrong destination');for(const r of ladder.rungs)if(r.some(c=>r.includes(c+1)))throw Error('Adjacent rungs');if(ladder.results[4]==='1')hyeTeam1++;pairs.add(ladder.results.slice(0,4).map((t,i)=>t===ladder.results[4]?i:'').filter(x=>x!=='').join(','));}return {hyeTeam1,pairs:pairs.size};})()`);assert.equal(result.pairs,6);assert(result.hyeTeam1>4500&&result.hyeTeam1<5500);});
test('Repeated assignment allows just one pending round',async()=>{const a=setup();await a.init();await a.act('assignSharedTeams();assignSharedTeams();assignSharedTeams()');assert.equal(a.state().sharedRounds.length,1);await a.act('assignSharedTeams()');assert.equal(a.state().sharedRounds.length,1);});
test('Cancel removes only the pending assignment',async()=>{const a=setup({sharedRounds:[round('saved')],activeSharedRoundId:'saved'});await a.init();await a.act('assignSharedTeams()');await a.act('cancelSharedAssignment()');assert.deepEqual(a.state().sharedRounds.map(x=>x.id),['saved']);});
test('Saving a winner updates wins and losses once',async()=>{const a=setup({sharedRounds:[round('pending',null)],activeSharedRoundId:'pending'});await a.init();await a.act("selectedSharedWinner=1;selectedSharedRoundId='pending';recordSharedWinner()");const stats=clone(a.run('getPlayerStats()'));assert.equal(stats.남우.wins,1);assert.equal(stats.민진.losses,1);assert.equal(stats.민경.losses,1);assert.equal(a.state().matches.length,0);await a.act("selectedSharedWinner=2;selectedSharedRoundId='pending';recordSharedWinner()");assert.equal(a.state().sharedRounds[0].winnerTeam,1);});
test('Combination and synergy totals ignore pending rounds',async()=>{const a=setup({sharedRounds:[round('one',1),round('two',2),round('pending',null)],activeSharedRoundId:'pending'});await a.init();assert(a.el('sharedCombinationCounts').innerHTML.includes('2전'));assert(a.el('sharedCombinationCounts').innerHTML.includes('1승'));assert(a.el('sharedSynergyCounts').innerHTML.includes('승률 50%'));assert(!a.el('sharedSynergyCounts').innerHTML.includes('혜빈'));});
test('History splits five recent rows and retains correct ordinal numbering',async()=>{const a=setup({matches:Array.from({length:7},(_,i)=>({id:`m${i}`,date:'2026-09-30',changes:amounts(i)})),sharedRounds:Array.from({length:8},(_,i)=>round(`r${i}`))});await a.init();assert.equal((a.el('historyBody').innerHTML.match(/<tr>/g)||[]).length,5);assert(a.el('historyBody').innerHTML.includes('15회차'));assert.equal((a.el('historyOlderBody').innerHTML.match(/<tr>/g)||[]).length,10);assert.equal((a.el('sharedHistoryBody').innerHTML.match(/shared-round-record/g)||[]).length,8);assert(a.el('sharedHistoryBody').innerHTML.includes('3경기'));});
test('Stake selection makes no server call and leaves the draft intact',async()=>{const a=setup({settlement:ledger({draft:amounts(3000)})});await a.init();const writes=a.writes;await a.act('for(let i=0;i<100;i++)selectSettlementStake(i%2?5000:3000)');assert.equal(a.writes,writes);assert.equal(a.state().settlement.draft.남우,3000);assert.equal(a.choices[1].attrs['aria-pressed'],'true');});
test('Amount click captures chosen stake even when selection changes during save',async()=>{const a=setup({settlement:ledger()});await a.init();await a.act("selectSettlementStake(5000);adjustSettlementAmount('남우',1);selectSettlementStake(3000)");assert.equal(a.state().settlement.draft.남우,5000);assert.equal(a.choices[0].attrs['aria-pressed'],'true');});
test('Saving a ledger round resets its draft and never writes scoreboard matches',async()=>{const a=setup({settlement:ledger({draft:amounts(5000)})});await a.init();await a.act('saveSettlementRound();saveSettlementRound()');assert.equal(a.state().settlement.rounds.length,1);assert.equal(a.state().settlement.draft.남우,0);assert.equal(a.run('settlementTotals(state.settlement).남우'),5000);assert.equal(a.state().matches.length,0);});
test('Two screens undoing the same round remove only that round',async()=>{const initial={revision:1,settlement:ledger({rounds:[{id:'a',changes:amounts(3000)},{id:'b',changes:amounts(5000)}]})};const a=setup(initial);await a.init();a.conflict(()=>{const s=a.server;s.settlement.rounds.pop();s.revision++;a.server=s;});await a.act('undoSettlementRound()');assert.deepEqual(a.state().settlement.rounds.map(x=>x.id),['a']);});
test('A stale click cannot modify a different settlement session',async()=>{const a=setup({revision:1,settlement:ledger()});await a.init();a.server={revision:2,settlement:ledger({id:'new-session'})};await a.act("adjustSettlementAmount('남우',1)");assert.equal(a.state().settlement.draft.남우,0);});
test('Finish keeps the current draft, allows a new day, and archives the old day',async()=>{const a=setup({settlement:ledger({draft:amounts(5000)})});await a.init();await a.act('finishDailySettlement()');await a.el('confirmSettlementFinish').listeners.click();assert.equal(a.state().settlement.closed,true);assert.equal(a.state().settlement.rounds.length,1);assert.equal(a.state().matches.length,0);assert.equal(a.el('startSettlement').hidden,false);await a.act('startDailySettlement()');assert.equal(a.state().settlementHistory.length,1);assert.equal(a.state().settlementHistory[0].rounds[0].changes.남우,5000);assert.equal(a.state().settlement.rounds.length,0);assert.equal(a.state().settlement.closed,false);});
test('Cancel confirmation keeps the ledger untouched',async()=>{const a=setup({settlement:ledger({rounds:[{id:'a',changes:amounts(3000)}]})},{confirm:false});await a.init();await a.act('undoSettlementRound();finishDailySettlement()');await a.el('cancelSettlementFinish').listeners.click();assert.equal(a.state().settlement.rounds.length,1);assert.equal(a.state().settlement.closed,false);assert.equal(a.writes,0);});
test('Optimistic retry preserves a concurrent result addition',async()=>{const a=setup({revision:1});await a.init();a.conflict(()=>{const s=a.server;s.matches=[{id:'other',date:'2026-09-30',changes:amounts(3000)}];s.revision++;a.server=s;});await a.act("enqueue(base=>({...base,matches:[...base.matches,{id:'mine',date:'2026-09-30',changes:{南:0}}]}))");assert.deepEqual(a.state().matches.map(x=>x.id),['other','mine']);assert.equal(a.state().revision,3);});
test('Save failure preserves state and unlocks controls',async()=>{const a=setup({settlement:ledger()});await a.init();a.setWriteError(Error('offline'));await a.act("adjustSettlementAmount('남우',1)");assert.equal(a.state().settlement.draft.남우,0);assert.equal(a.run('working'),false);assert(a.el('toast').textContent.includes('서버 저장에 실패'));assert.equal(a.el('drawSharedTeams').disabled,false);});
test('Realtime subscription and visibility fallback refresh remote changes',async()=>{const a=setup({revision:1});await a.init();assert.equal(a.subscriptions.length,1);assert.equal(a.intervals.length,1);a.server={revision:2,matches:[{id:'remote',date:'2026-09-30',changes:amounts(3000)}]};a.subscriptions[0]();await a.run('pending');assert.equal(a.state().matches[0].id,'remote');});
test('Delete confirmed record updates counts; cancel does not mutate',async()=>{const a=setup({sharedRounds:[round('delete')]});await a.init();await a.act("pendingSharedDeleteId='delete';document.getElementById('cancelSharedDelete').listeners.click()");assert.equal(a.state().sharedRounds.length,1);a.run("pendingSharedDeleteId='delete'");await a.el('confirmSharedDelete').listeners.click();assert.equal(a.state().sharedRounds.length,0);assert.equal(a.el('sharedHistoryCount').textContent,'0 ROUNDS');});
test('Reset removes added records and ledger archives but retains fixed baseline',async()=>{const a=setup({matches:[{id:'m',changes:amounts(3000)}],sharedRounds:[round('r')],settlement:ledger(),settlementHistory:[ledger({id:'archive',closed:true})]});await a.init();await a.el('confirmReset').listeners.click();assert.equal(a.state().matches.length,0);assert.equal(a.state().settlementHistory.length,0);assert.equal(a.state().settlement,null);assert.equal(a.el('totalGames').textContent,8);});
test('Invalid money input rejects decimal and unsafe numbers; negative integer saves',async()=>{const a=setup();await a.init();a.el('matchDate').value='2026-09-30';for(const id of ['amountSeonggu','amountNamu','amountTaewon','amountMinjin'])a.el(id).value='0';a.el('amountMinjin').value='-3000.5';await a.el('resultForm').listeners.submit({preventDefault(){}});assert.equal(a.writes,0);a.el('amountMinjin').value='9007199254740992';await a.el('resultForm').listeners.submit({preventDefault(){}});assert.equal(a.writes,0);a.el('amountMinjin').value='-3000';await a.el('resultForm').listeners.submit({preventDefault(){}});assert.equal(a.state().matches[0].changes.민진,-3000);});
(async()=>{let passed=0;for(const [name,fn] of cases){try{await fn();console.log(`PASS ${name}`);passed++;}catch(error){console.error(`FAIL ${name}\n${error.stack}`);}}console.log(`${passed}/${cases.length} passed`);if(passed!==cases.length)process.exitCode=1;})();
